A, B, C = map(float, input().split())
tri = float((A*C)/2)
cir = float(3.14159*(C**2))
tra = float((A+B)*C/2)
qua = float(B**2)
ret = float(A*B)
print(f"TRIANGULO: {tri:.3f}")
print(f"CIRCULO: {cir:.3f}")
print(f"TRAPEZIO: {tra:.3f}")
print(f"QUADRADO: {qua:.3f}")
print(f"RETANGULO: {ret:.3f}")
#0.047 / 28.05.2021 / 1
